#Download from nvidia
from nvidia/cuda:10.1-runtime


# Update Software repository
RUN apt-get update
RUN apt-get install -y python python-pip python-dev wget

RUN pip install --upgrade pip
RUN pip install tensorflow-gpu
COPY workflow.sh .
COPY cifar10* ./

ENTRYPOINT ["/workflow.sh"]
